services:
  mongo:
    image: mongo:latest
    container_name: db
    env_file:
      - mongo.env
    ports:
      - 27017:27017
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      mongo:
        condition: service_healthy